- src/lib/avatar.ts
- src/lib/babylon/emotes.ts
- src/lib/babylon/render.ts
- src/lib/babylon/slots.ts
- src/lib/wearable.ts
> feat: added support for nft emotes

- src/lib/babylon/scene.ts
> fix: give hair and skin materials alpha of 1

- src/lib/babylon/render.ts
- src/lib/babylon/scene.ts
- src/lib/babylon/wearable.ts
> fix: tint hair and skin

- README.md
- src/hooks/useAsync.ts
- src/hooks/useConfig.ts
- src/hooks/useOptions.ts
- src/index.tsx
> fix: hot reload

- src/lib/babylon/emotes.ts
Closes #22
Ability to play emotes passed via urn/urn/base64
> feat: play non-target emotes

- src/lib/babylon/body.ts
- src/lib/babylon/render.ts
- src/lib/babylon/slots.ts
> fix: hidden body shape

- src/hooks/useOverrides.ts
> feat: send ready message

- package-lock.json
- package.json
- src/hooks/useOptions.ts
- src/lib/config.ts
**Note**: bumping `@dcl/schemas` is needed before releasing this. (Vercel deploy failed due to that)
> feat: add disableDefaultEmotes prop support and disabled the default emote if so

- README.md
- package-lock.json
- package.json
- src/hooks/useOptions.ts
- src/lib/babylon/scene.ts
- src/lib/config.ts
This PR adds a `projection` option that can be set as `perspective` (the one we already had) or `orthographic`. I also added options to set the camera position manually.
> feat: added support for orthographic projection and custom camera position

- README.md
- package-lock.json
- package.json
- src/components/Preview/Preview.css
- src/components/Preview/Preview.tsx
- src/config/env/dev.json
- src/config/env/prod.json
- src/config/env/stg.json
- src/config/index.ts
- src/hooks/useOptions.ts
- src/lib/api/nft.ts
- src/lib/api/peer.ts
- src/lib/config.ts
This PR adds the ability to use custom peer and nft server urls. It also adds the ability to disable CSS transitons (useful for automation). Finally it replaces the outdated `PreviewEnv` with [`@dcl/ui-env`](https://github.com/decentraland/ui-env)
> feat: added peerUrl, nftServerUrl and disableFadeEffect functionality

- src/lib/config.ts
This PR fixes the support for emote from URN, URL of base64, which was broken with the last release
> fix: builder

- README.md
- package-lock.json
- package.json
- src/hooks/useOptions.ts
- src/lib/babylon/scene.ts
- src/lib/config.ts
The build will be broken until the common-schemas is released and bumped in here.
> feat: Add cylinder to scene to show animation boundaries

- README.md
- package-lock.json
- package.json
- src/hooks/useOptions.ts
- src/lib/babylon/scene.ts
- src/lib/config.ts
This PR adds a thin box around the model to show thumbnail screenshot boundaries
depends on: https://github.com/decentraland/common-schemas/pull/138
> feat: Show thumbnail boundaries

- package-lock.json
- package.json
- src/lib/babylon/emote.ts
- src/lib/emote-events.ts
This PR adds the event `animation_playing` and sends the current animation playing frame using the event emitter
depends on: https://github.com/decentraland/common-schemas/pull/143
> feat: Add animation playing event

- README.md
- package-lock.json
- package.json
- src/components/Preview/Preview.tsx
- src/hooks/useOptions.ts
- src/lib/config.ts
This PR adds the preview type param to allow choosing the PreviewType.
> feat: Add preview type param

- README.md
This PR adds some RPC methods and events that were missing and fixes an inexisting type
> chore: added missing documentation

- .github/workflows/set-rollout-manual.yaml
- .github/workflows/set-rollout.yaml
This PR updates the ubuntu version in github actions
> chore: Update ubuntu version in actions

- src/lib/api/peer.ts
This PR changes the deprecated profile endpoint so it uses the new one.
> fix: Change deprecated profile endpoint

- package-lock.json
- package.json
- src/hooks/useOptions.ts
- src/lib/babylon/scene.ts
- src/lib/config.ts
This PR adds locking options to the wearable-preview.
> feat: Add locking options

- README.md
This PR adds to the readme the new parameters.
> fix: Update readme with new parameters

- package-lock.json
- package.json
- src/lib/babylon/emote.ts
- src/lib/babylon/scene.ts
- src/lib/config.ts
- src/lib/emote.ts
Add emote 2.0 logic with additional geometry and sound
> feat: add sound and geometry logic

- src/lib/config.ts
Move camara z position back to previous value
> fix: move z camara position to previous value

- src/lib/babylon/emote.ts
Fix only once emotes running in loop
> fix: loop emotes

- README.md
- src/lib/config.ts
> feat: Accept numbered default profiles

- package-lock.json
- package.json
- src/components/Preview/Preview.tsx
- src/lib/emote-events.ts
- src/lib/emote.ts
This PR updates the schemas according to the new events library.
> fix: Update schema

- package-lock.json
- package.json
- src/config/env/dev.json
This PR upgrades the package `@dcl/schemas` and changes the dev network from `mumbai` to `amoy`
> feat: Upgrade packages
