decentraland/wearable-preview

package-lock.json, package.json, src/lib/babylon/emote.ts, src/lib/babylon/mappings.ts, src/lib/babylon/render.ts, src/lib/babylon/slots.ts, src/lib/babylon/utils.ts, src/lib/babylon/wearable.ts, src/lib/config.ts, src/lib/emote.ts, src/lib/representation.ts, src/lib/wearable.ts
Nowadays, the wearable preview renders the IDLE emote as the default one, that means that it gets loaded before getting the message with the blob with the emote we want to render from the builder. That means that the `getLength` will be emitted twice, once for the idle and another once the blob is parsed.
=> feat: Add support for "null" emote

.gitignore, package-lock.json, package.json, src/components/Preview/Preview.tsx, src/hooks/useController.ts, src/lib/babylon/emote.ts, src/lib/emote-events.ts, src/lib/emote.ts
Blocked by https://github.com/decentraland/common-schemas/pull/114
This PR adds support for a new `EMOTE_EVENT` message, which can have different types: `animation_play`, `animation_pause`, `animation_loop` and `animation_end`. These are native observable events in babylon, and they are being forwarded via `postMessage` so they can be handled on the main frame exposed through a regular event emitter.
=> feat: added support for emote events

src/components/Preview/Preview.tsx
This PR fixes the controller play when the loaded scene doesn't contain an emote.
=> fix: Fix to play the controller when the loaded scene contains an emote

src/lib/babylon/mappings.ts
The current logic for mappings only works for wearables that come from the catalyst or the builder server (because it relied on the url having a `content/contents` section), but it doesn't work for wearables with blobs (ie. wearables from a zip file). this PR fixes that.
=> fix: mappings for wearables with blobs

src/lib/config.ts, src/lib/zoom.ts
The `zoom` option can be set by the user as a value between 0 and 100. This value is then converted to a value between 1 and 2.8 (which are the actual valid values). The conversion from 0-100 to 1-2.8 range was done when the value was parsed from the query param. This means that when the `zoom` value was passed via `postMessage`, the value would be used as is, instead of converted to the right range, resulting in a huge value and not working as expected.
I moved the logic to convert the value to the right range into a separate function from the parsing, and I used it within the `createConfig` function, which is used either if the update is coming from a query param or from a postMessage update.
=> fix: using the zoom via postMessage

src/lib/babylon/emote.ts
This PR updates the stop controller logic and removes the `loop` condition on the event: `onAnimationEnd`.
=> Fix: Stop loop animations

package-lock.json, package.json, src/lib/api/peer.ts, src/lib/babylon/emote.ts, src/lib/babylon/mappings.ts, src/lib/babylon/render.ts, src/lib/babylon/scene.ts, src/lib/babylon/slots.ts, src/lib/babylon/utils.ts, src/lib/babylon/wearable.ts, src/lib/config.ts, src/lib/emote.ts, src/lib/json.ts, src/lib/representation.ts, src/lib/urn.ts, src/lib/wearable.ts, src/lib/zoom.ts
This PR adds support for emotes that are of `EntityType.EMOTE` and with the schema of the ADR-74. In order to support this, instead of using the lambdas, we fetch the entities and then convert them to wearable or emote definitions. This is because we can't fetch wearable and emote definitions from the same lambda, and we need to be able to get these definitions from the URNs, and by looking just at the URNs we cannot tell if they are wearables or emotes. So since we can't tell beforehand what they are, we can't know which lambda to hit. So instead we use the `content/entities/active` endpoint and fetch the entities by pointer (which is the URN). 
Then I refactored the `config.wearables` prop to be just a `WearableDefinition[]` instead of a mix of `WearableDefinition` and …
=> fix: add support for ADR74 emotes

README.md, src/components/Preview/Preview.tsx, src/lib/api/peer.ts
Currently, the emotes are not playing when the camera is static.
=> fix: Play emotes when camera is static

package-lock.json, package.json, src/lib/api/peer.ts, src/lib/babylon/utils.ts, src/lib/babylon/wearable.ts, src/lib/config.ts, src/lib/representation.ts
This PR adds support for `EmoteWithBlobs` to be passed via the `options.blob` property. Up until now we do support passing emotes as blobs but they are passed as `WearableWithBlobs` type, with an `emoteDataV0` property. This property will eventually be deprecated, so the right way to pass emotes should be as `EmoteWithBlobs`.
=> feat: support blobs that are ADR74 emotes

package-lock.json, package.json, src/lib/babylon/emote.ts, src/lib/emote.ts, src/lib/representation.ts
Remove support for `emoteDataV0`
=> chore: remove support for legacy emotes

src/lib/babylon/emote.ts
This PR fixes the starting frame when a looped emote ends and was used the Go To feature.
=> fix: Starting emote frame when looping from a GoTo

src/lib/babylon/emote.ts
This PR fixes misplaced wearables when playing emotes.
replicable error:
- https://wearable-preview.decentraland.org/?contract=0x705652b66a12dcf782b0b3d5673fbf0c1797eba2&item=17&profile=default&emote=fashion-2
- https://wearable-preview.decentraland.org?contract=0x705652b66a12dcf782b0b3d5673fbf0c1797eba2&item=4&profile=default&emote=fashion-2
=> fix: Misplaced wearable when playing an emote

src/lib/config.ts
This PR sanitizes the profile param passed in the query params to avoid sending requests with invalid parameters on the Catalyst server.
Closes: #75
=> feat: Sanitize profile param

src/lib/config.ts
Some emotes are not being rendered correctly are they are setting the default position of wearables in 0,0,0.
This PRs removes the logic of setting an emote in the config when we are rendering a specific remote
New
https://wearable-preview-git-fix-emote-rendering-decentraland1.vercel.app/?contract=0x705652b66a12dcf782b0b3d5673fbf0c1797eba2&item=17&profile=default&emote=fashion-2
https://wearable-preview-git-fix-emote-rendering-decentraland1.vercel.app/?contract=0x6f8026ecc425d548ea2f953b471b7440780d505b&item=0
https://wearable-preview-git-fix-emote-rendering-decentraland1.vercel.app/?contract=0x9a9b2acf09adca5f626113ff6fa74050a3645044&item=0
Before
https://wearable-preview.decentraland.org/?contract=0x705652b66a12dcf782b0b3d5673fbf0c1797eba2&item=17&profile=default&emote=fashion-2 …
=> fix: emote rendering

src/lib/babylon/emote.ts
For some reason, props animations where being loaded and played on loop. This PR stops all animations before create the emote animationGroup that will be in charge of playing and stoping animations using the controller events
Previously
https://wearable-preview.decentraland.org/?profile=default&urn=urn:decentraland:off-chain:base-avatars:keanu_hair&urn=urn:decentraland:off-chain:base-avatars:f_blue_elegant_shirt&urn=urn:decentraland:off-chain:base-avatars:f_yoga_trousers&skin=ffddbb&hair=8b2014&eyes=5e3831&bodyShape=urn:decentraland:off-chain:base-avatars:BaseFemale&emote=idle&wheelZoom=1.5&wheelStart=100&disableBackground&disableAutoRotate&env=dev&urn=urn:decentraland:mumbai:collections-v2:0xcf55d86aee32fe0073be7706c8a8a48b091611f7:0
=> fix: prop animation running in loop

src/lib/config.ts
When a profile is defined and that profile has an avatar then we are disabling the default wearables to be up to date with "Body fallback" in [ADR-239](https://adr.decentraland.org/adr/ADR-239)
=> feat: disable default wearables when there is an avatar

.github/workflows/build-release.yaml
Fix `Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory` error
=> fix: change node space size

src/lib/babylon/emote.ts
Prop animations can be created without bones. We are currently checking that the target of the animation is any of the avialable nodes of the avatar causing it to not work. This PR ignores that check for props animation group
=> fix: prop animation without bone link

README.md, package-lock.json, package.json, src/hooks/useOptions.ts, src/lib/babylon/scene.ts, src/lib/config.ts
This PR adds the ability to increase the zoom via de `zoomScale` property. We were limiting the max zoom to a low value because it started clipping beyond a certain zoom level, but it was because of the `camera.minZ` value being too high, i set it to `0.1` and now we can put the camera really close to the avatar without clipping.
We need to be able to put the camera very close to the avatar face to generate the face snapshots for the profile-images research. 
I didn't just increase the `MAX_ZOOM` value because that would change the way the zoom property behaves, and I didn't want to break anything in production. So instead I added this `zoomScale` which is 1 by default, but if necessary it can be used to make the zoom go beyond the `MAX_ZOOM` level.
=> feat: added zoom scale param

src/lib/config.ts
A new change was done in platform side that adds the token id to the urns to uniquely identify an nft. This "extended" versions of urns are the ones that appear in the users profile but are not supported when fetching entities using `/entities/active` endpoint.
This PR adds function to get previous unextended version of urn to fetch the entities
=> fix: do not fetch with extended urns

package-lock.json, package.json, src/lib/babylon/emote.ts
This PR changes the `EventEmitter` class, that comes from the node std for a library built to work in both browser and node environments. The new library includes type checking for the events and the handlers as well.
=> feat: Use Events library for Emote events

src/lib/config.ts
This PR addresses how third-party wearables are processed. When an extended URN is received (i.e., urn.Split(':').Length > 6), it cuts off the last part and returns the shortened version. This is necessary because the /entities/active endpoint from Catalysts' content servers expects the shortened URN to return the wearable/emote metadata.
The issue was that wearables from third-party providers contain 7 parts, causing the code to mistakenly treat them as extended URNs, which is not the case. Third-party wearables have an additional part but that part do not represent a token id (which is the part that should be removed), so we need to call the Catalysts endpoint using the entire URN received instead of shortening it.
The changes in this PR prevent the removal of the last part of the URN …
=> fix: third-party wearable rendering

src/lib/config.ts
This PR makes it possible for the site to process the new wearables' third party URNs.
The URN in the user's profile is represented as:
`urn:decentraland:amoy:collections-thirdparty:back-to-the-future:amoy-eb54:tuxedo-6751:amoy:0x1d9fb685c257e74f869ba302e260c0b68f5ebb37:15`
And we need to remove the network, contract and token id parts to get a valid pointer.
=> fix: Allow new third parties URN

src/lib/babylon/emote.ts
Fixed avatar animation getting stuck on first frame with non-standard skeleton hierarchy.
Some wearable assets use a non-standard skeleton hierarchy where the Armature node and bones have numeric suffixes (e.g., Armature.001, Avatar_Head.001). This caused issues with emotes that use a mixed animation approach, where the main motion is applied to the Armature node while shorter animations are applied to individual bones to position the avatar correctly.
Previously, the animation targeting was strict and required exact node name matches, causing animations to fail when the asset used numbered suffixes. This resulted in the avatar appearing stuck on the first frame while props animated correctly.
The fix modifies the animation targeting logic to ignore numeric suffixes when matching node …
=> fix: patch non-standard skeleton hierarchies

src/lib/babylon/emote.ts
Recent changes to handle non-standard node names (e.g., "Armature.001") introduced a regression where some avatar animations stopped working. The fix for numbered suffixes removed the logic that handled single-animation cases, causing default animations like idle to not play.
Restored and enhanced the animation detection to consider three cases:
1. Single animation case - if there's only one animation group, it must be for the avatar
2. Group name - if it contains "avatar" (e.g., "Horse_Avatar")
3. Target name - if it targets avatar bones (e.g., "Avatar_Head")
- Verified default idle animation plays correctly
- Tested with both single-animation emotes and prop-based emotes
- Confirmed it works with standard and non-standard node naming
=> fix: default emotes
